# -*- coding: utf-8 -*-
"""Prodigy_DS_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iOO7n9zREWZPMKhCep1H5TBvw3gBjsCX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

data= pd.read_csv("/content/full.csv")
data.head()

data.tail()

data.index

data.shape

data.size

data.columns

data.describe()

data.info()

# Cleaning Data
missing_data = data.isnull().sum()
missing_data

data = data.drop_duplicates()
data.head(8)

data['Age'] = pd.to_numeric(data['Age'], errors='coerce')
data['Fare'] = pd.to_numeric(data['Fare'], errors='coerce')

# Exploratory Data Analysis (EDA)
summary_stats = data.describe()
print(summary_stats)

# Univariate Analysis:
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.histplot(data['Age'].dropna(), kde=True)
plt.title('Age Distribution')
plt.subplot(1, 2, 2)
sns.countplot(data['Sex'])
plt.title('Gender Distribution')
plt.show()

# Categorical Variables:
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.countplot(data['Pclass'])
plt.title('Pclass Distribution')
plt.subplot(1, 2, 2)
sns.countplot(data['Embarked'])
plt.title('Embarked Distribution')
plt.show()

# Survival Analysis:
survival_rate_by_class = data.groupby('Pclass')['Survived'].mean()
survival_rate_by_sex = data.groupby('Sex')['Survived'].mean()

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.barplot(x=survival_rate_by_class.index, y=survival_rate_by_class.values)
plt.title('Survival Rate by Pclass')
plt.subplot(1, 2, 2)
sns.barplot(x=survival_rate_by_sex.index, y=survival_rate_by_sex.values)
plt.title('Survival Rate by Sex')
plt.show()

# Visualizing Survival by Age:
plt.figure(figsize=(9, 6))
sns.boxplot(x='Survived', y='Age', data=data)
plt.title('Survival by Age')
plt.xticks([0, 1], ['Not Survived', 'Survived'])
plt.show()

data['FamilySize'] = data['SibSp'] + data['Parch']

sns.pairplot(data, vars=['Age', 'Fare', 'FamilySize'], hue='Survived')
plt.suptitle('Pair Plot of Age, Fare, and FamilySize')
plt.show()

plt.figure(figsize=(9, 6))
data['Title'] = data['Name'].str.extract(' ([A-Za-z]+)\.')
sns.countplot(data['Title'])
plt.title('Passenger Titles')
plt.xticks(rotation=45)
plt.show()

# Survival by Title:
title_survival_rate = data.groupby('Title')['Survived'].mean()
plt.figure(figsize=(12, 5))
sns.barplot(x=title_survival_rate.index, y=title_survival_rate.values)
plt.title('Survival Rate by Title')
plt.xticks(rotation=45)
plt.show()